language: objective-c
osx_image: xcode8.2
sudo: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
matrix:
  include:
    - osx_image: xcode8.3.1
      env: PLATFORM=ios
    - osx_image: xcode8.3.1
      env: PLATFORM=macos
    - osx_image: xcode8.3.1
      env: PLATFORM=tvos
	- osx_image: xcode8.3.1
	  env: PLATFORM=watchos
before_install:
  - make install
script:
  - make $PLATFORM
