os: osx
language: objective-c
sudo: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
matrix:
  include:
    - os: osx
      env: PLATFORM=ios
    - os: osx
      env: PLATFORM=macos
    - os: osx
      env: PLATFORM=tvos
    - os: osx
      env: PLATFORM=watchos
install:
  - make install
script:
  - make $PLATFORM
