osx_image: xcode9.1
language: objective-c
sudo: false
xcode_project: UCLKit.xcodeproj
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - FRAMEWORK_NAME=UCLKit
matrix:
  include:
  - xcode_scheme: UCLKit iOS
    env: PLATFORM=ios
  - xcode_scheme: UCLKit macOS
    env: PLATFORM=macos
  - xcode_scheme: UCLKit tvOS
    env: PLATFORM=tvos
  - xcode_scheme: UCLKit watchOS
    env: PLATFORM=watchos
before_install:
- make install
script:
- make $PLATFORM
after_success:
  - bash <(curl -s https://codecov.io/bash) -J $PLATFORM
before_deploy:
- make deploy
deploy:
  provider: releases
  api_key:
    secure: gH4AbfSyV2L7KiwWc3RwbyBhnWY2kp6UWce/vEWlUVQGdygzU7xI9gDyysFW+ZRN8xXUy2b5fNXbYN/9NtOiDRMRNCGs8rbxKlnoDuYHca+FpRuSAvH8otxP8fYGH160fdfgkZDm+4Yr9q0w+RIUYwJayvvYKFVouCmNXWdMwHXOO3cMjF7gJIgTxMm1H6qLKuTgJf9gFDF/Fv7x5roaZxe3RT4rsxKNx/2jN6UuQmsbqqjbWzerwBj342E28SvQuixsnTEJuw/jP5jNOpT/P2TAI24erGGiwr7HZS6AM9L6nrVfGWd1ORjYVf+BIYorL6oXKfKl2AE+DxsaNLWvKLT+0CP9CC/zhrJ3OrVoJXvrj6y007vSpURVtn+eVCbemuZLbYVSkYWzwjI7qg4h8Rw0kVmEd8cUb+ekfdiAHWSRQJ40qEtfIN7msu4xdTvhrGihuPVSkOBJmqWbk5f1VOfCFR6Qtnlz0lAlDvrDz/Q5GdlTeZNmrTkJJASs5MhWFJoOQB+9HKw7knWqlShYcFn2VbfTz8vRW69djxaNkUQmlEAYtBwpT2GIgfOmXYs/njh2aQotMNQJH2q+zeSTXc+UqxnjLXxlYRouj0+iwb8ZfO4zY3zj53D6u1a6IROG239dwoDgYXEk7Ugjyu203Z1bkgJtl+FFeUd4mfR0kHc=
  file: UCLKit.framework.zip
  skip_cleanup: true
  on:
    repo: tiferrei/UCLKit
    tags: true
