language: objective-c
sudo: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
matrix:
  include:
    env:
      - PLATFORM=ios
      - PLATFORM=macos
      - PLATFORM=tvos
      - PLATFORM=watchos
install:
  - make install
script:
  - make $PLATFORM
