version: 2

jobs:
  dependencies:
    macos:
      xcode: "9.3.0"
    working_directory: ~/UCLKit
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: make install
      - save_cache:
          key: UCLKit-build-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/UCLKit

  macOS:
    macos:
      xcode: "9.3.0"
    working_directory: ~/UCLKit
    steps:
      - restore_cache:
          keys:
            - UCLKit-build-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Build and run macOS tests
          command: make macos

  iOS:
    macos:
      xcode: "9.3.0"
    working_directory: ~/UCLKit
    steps:
      - restore_cache:
          keys:
            - UCLKit-build-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Build and run macOS tests
          command: make macos

  watchOS:
    macos:
      xcode: "9.3.0"
    working_directory: ~/UCLKit
    steps:
      - restore_cache:
          keys:
            - UCLKit-build-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Build and run macOS tests
          command: make macos

  tvOS:
    macos:
      xcode: "9.3.0"
    working_directory: ~/UCLKit
    steps:
      - restore_cache:
          keys:
            - UCLKit-build-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Build and run macOS tests
          command: make macos

  Linux:
    docker:
      - image: swift:4.1
    steps:
      - checkout
      - run:
          name: Compile code with optimisations
          command: swift build -c release

  deploy:
    macos:
      xcode: "9.3.0"
    working_directory: ~/UCLKit
    steps:
      - restore_cache:
          keys:
            - UCLKit-build-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Exporting Framework
          command: make deploy
      - store_artifacts:
          path: ./UCLKit.framework.zip
          destination: UCLKit.zip

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - dependencies
      - macOS:
          requires:
            - dependencies
      - iOS:
          requires:
            - dependencies
      - watchOS:
          requires:
            - dependencies
      - tvOS:
          requires:
            - dependencies
      - Linux:
          requires:
            - dependencies
      - deploy:
          requires:
            - macOS
            - iOS
            - watchOS
            - tvOS
            - Linux
          filters:
            tags:
              only: /.*/
            branches:
              only: master
