version: 2

jobs:
  Xcode:
    macos:
      xcode: "10.2.0"
    working_directory: ~/UCLKit
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: make install
      - save_cache:
          key: UCLKit-build-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/UCLKit

  macOS:
    macos:
      xcode: "10.2.0"
    working_directory: ~/UCLKit
    steps:
      - restore_cache:
          keys:
            - UCLKit-build-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Build and run macOS tests
          command: make macos

  iOS:
    macos:
      xcode: "10.2.0"
    working_directory: ~/UCLKit
    steps:
      - restore_cache:
          keys:
            - UCLKit-build-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Build and run macOS tests
          command: make macos

  watchOS:
    macos:
      xcode: "10.2.0"
    working_directory: ~/UCLKit
    steps:
      - restore_cache:
          keys:
            - UCLKit-build-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Build and run macOS tests
          command: make macos

  tvOS:
    macos:
      xcode: "10.2.0"
    working_directory: ~/UCLKit
    steps:
      - restore_cache:
          keys:
            - UCLKit-build-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Build and run macOS tests
          command: make macos

  Swift (Linux):
    docker:
        - image: swift:4.2
    steps:
      - checkout
      - run:
          name: Build and run Linux tests 
          command: swift test

  Swift (Darwin):
    macos:
      xcode: "10.2.0"
    steps:
      - checkout
      - run:
          name: Build and run tests with Swift Package Manager
          command: swift test

  deploy:
    macos:
      xcode: "10.2.0"
    working_directory: ~/UCLKit
    steps:
      - restore_cache:
          keys:
            - UCLKit-build-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Exporting Framework
          command: make deploy
      - store_artifacts:
          path: ./UCLKit.framework.zip
          destination: UCLKit.zip

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - Xcode 
      - macOS:
          requires:
            - Xcode 
      - iOS:
          requires:
            - Xcode 
      - watchOS:
          requires:
            - Xcode 
      - tvOS:
          requires:
            - Xcode 
      - Swift (Darwin)
      - Swift (Linux)
      - deploy:
          requires:
            - macOS
            - iOS
            - watchOS
            - tvOS
            - Swift (Darwin)
            - Swift (Linux)
          filters:
            tags:
              only: /.*/
            branches:
              only: master
